In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.datasets import load_digits
digit=load_digits()

In [4]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
digit.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [6]:
df= pd.DataFrame(digit.data,columns=digit.feature_names)

In [7]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [8]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [11]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
df['target']=digit.target

In [10]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [12]:
df[df['target']==9]

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
9           0.0        0.0       11.0       12.0        0.0        0.0   
19          0.0        0.0        6.0       14.0        4.0        0.0   
29          0.0        0.0        9.0       13.0        7.0        0.0   
31          0.0        0.0        2.0       13.0        8.0        0.0   
37          0.0        0.0       13.0       10.0        1.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1759        0.0        0.0        7.0       16.0        9.0        8.0   
1772        0.0        0.0        5.0       14.0       11.0        8.0   
1786        0.0        0.0        4.0       14.0       15.0        6.0   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
9           0.0        0.0        0.0        2.0  ...        0.0        0.0   
19          0.0        0.0        0.0        0.0  ...        2.0        0.0   
29          0.0        0.0        0.0        0.0  ...        2.0        0.0   
31          0.0        0.0        0.0        0.0  ...        2.0        0.0   
37          0.0        0.0        0.0        5.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1759        2.0        0.0        0.0        5.0  ...        0.0        0.0   
1772        0.0        0.0        0.0        4.0  ...        0.0        0.0   
1786        0.0        0.0        0.0        5.0  ...        0.0        0.0   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
9           0.0        9.0       12.0       13.0        3.0        0.0   
19          0.0        7.0       16.0       16.0       13.0       11.0   
29          0.0        7.0       12.0       12.0       12.0       11.0   
31          0.0        2.0       15.0       13.0       14.0       13.0   
37          0.0       13.0       13.0       15.0       16.0       13.0   
...         ...        ...        ...        ...        ...        ...   
1759        0.0        7.0       15.0       14.0        7.0        0.0   
1772        0.0        7.0       15.0       12.0        5.0        0.0   
1786        0.0        4.0       13.0       15.0        9.0        0.0   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   

      pixel_7_7  target  
9           0.0       9  
19          1.0       9  
29          0.0       9  
31          2.0       9  
37          0.0       9  
...         ...     ...  
1759        0.0       9  
1772        0.0       9  
1786        0.0       9  
1792        0.0       9  
1795        0.0       9  

[180 rows x 65 columns]

In [16]:
x= df.drop(['target'],axis=1)
y= df.target

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [18]:
len(x_train)

1257

In [19]:
len(x_test)

540

##  using rbf kernel

In [20]:
from sklearn.svm import SVC
rbf= SVC(kernel='rbf')

In [21]:
rbf.fit(x_train,y_train)

SVC()

In [22]:
rbf.score(x_test,y_test)

0.9851851851851852

###  using linear kernel

In [23]:
linear_model = SVC(kernel='linear')
linear_model.fit(x_train,y_train)

SVC(kernel='linear')

In [24]:
linear_model.score(x_test,y_test)

0.9796296296296296

###  Parameter tuning:

In [50]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.1,1,10,100], 'gamma':[1,0.1,0.01,0.001]}
grid = GridSearchCV(SVC(kernel='rbf'),param_grid,verbose=2)
grid.fit(x,y)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.3s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.3s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.3s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.3s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.2s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.2s
[CV] END ..................................C=0.1

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [27]:
print(grid.best_estimator_)

SVC(C=1, gamma=0.001)


In [28]:
rbf= SVC(kernel='rbf',C=1,gamma=0.001)

In [29]:
rbf.fit(x_train,y_train)

SVC(C=1, gamma=0.001)

In [30]:
rbf.score(x_test,y_test)

0.9907407407407407

In [31]:
rbf= SVC(kernel='rbf',C=1,gamma=0.01)
rbf.fit(x_train,y_train)
rbf.score(x_test,y_test)

0.6833333333333333

In [32]:
rbf= SVC(kernel='rbf',C=1,gamma=0.1)
rbf.fit(x_train,y_train)
rbf.score(x_test,y_test)

0.08703703703703704

In [35]:
rbf= SVC(kernel='rbf',C=1,gamma=0.0001)
rbf.fit(x_train,y_train)
rbf.score(x_test,y_test)

0.975925925925926

In [45]:
rbf= SVC(kernel='rbf',C=5,gamma=0.001)
rbf.fit(x_train,y_train)
rbf.score(x_test,y_test)

0.9888888888888889

In [49]:
rbf= SVC(kernel='rbf',C=500,gamma=0.001)
rbf.fit(x_train,y_train)
rbf.score(x_test,y_test)

0.9888888888888889